### ISSUE TITLE
Single Node openshift installation fails because of AntiAffinity

### ISSUE THREAD

**Issue by JesperAP** [ibm-mas/cli#1826]
### MAS CLI version

15.6.3

### CLI function used

install

### What happened?

I did a MAS install, with Manage. And the uds part of the pipeline failed because of this line:
"FAILED - RETRYING: [localhost]: Wait for the rhm-data-service to be ready (1 retries left)."

After investigating. I saw that "rhm-data-service-1" pod stays on pending (rhm-data-service-0 is running fine).

I think it is because of this podAntiAffinity rule:

podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - rhm-data-service
          topologyKey: kubernetes.io/hostname

### Relevant log output

```shell
0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

**Comment by diegovisentin** [comment]
JFI: it seems the same of mine #1823 issue

**Comment by dflorea-onspark** [comment]
I have the same issue on several SNOs, on already existing instances as @diegovisentin or trying to install a new instance as @JesperAP. The issue arrived with an update on the IBM Metrics operator, on October 8th, on all my clusters, SNO or full OpenShift clusters, the issue is blocking only on SNO instances.
I tried to find a way to update the StatefulSet (either remove AntiAffinity rules, modify the number of the replicas in the StatefulSet, change labels, etc), no success whatsoever until now. I cannot find the definition of the StatefulSet in any CRD allowing it's modification, IMHO it may be hardcoded somewhere in an image.

**Comment by JesperAP** [comment]
Did someone already create a IBM support ticket? I need this fixed as I have some very strict deadlines coming up...

**Comment by diegovisentin** [comment]
This morning, a case was created.

While waiting for feedback from technical support, one option could be to use the August version of the CLI and then, if the installation works, proceed with the update.

**Comment by JesperAP** [comment]
> This morning, a case was created.
> 
> While waiting for feedback from technical support, one option could be to use the August version of the CLI and then, if the installation works, proceed with the update.

did you try this? Because I've tried a older version of the CLI and it still didn't work.

**Comment by diegovisentin** [comment]
> > This morning, a case was created.
> > While waiting for feedback from technical support, one option could be to use the August version of the CLI and then, if the installation works, proceed with the update.
> 
> did you try this? Because I've tried a older version of the CLI and it still didn't work.

No, it was just an idea. If you've tried it and it didn't work, then I think that indicates the problem might stem from components used by the CLI that have their own lifecycle (e.g., Ansible scripts).

**Comment by istrate** [comment]
Can you advise about what the IBM Metrics Operator you are using? This should have been fixed in v2.21.2. You can check the version using:
`oc get ClusterServiceVersion -n redhat-marketplace`

**Comment by JesperAP** [comment]
> Can you advise about what the IBM Metrics Operator you are using? This should have been fixed in v2.21.2. You can check the version using: `oc get ClusterServiceVersion -n redhat-marketplace`

ibm-metrics-operator.v2.21.2              IBM Metrics Operator          2.21.2

still having this issue.

**Comment by JesperAP** [comment]
I found the fix:

Delete the CustomResourceDefinitions "marketplaceconfig" and it will recreate without the AntiAffinity.

**Comment by JesperAP** [comment]
Sorry, not marketplaceconfig, but Meterbase: "rhm-marketplaceconfig-meterbase"

**Comment by pgodowski** [comment]
Is there a chance the workaround is applied, i.e. pinned CatalogSource for IBM Metrics operator, to deploy earlier version of Metrics Operator please?

**Comment by pgodowski** [comment]
manual workaround provided in https://github.com/ibm-mas/cli/issues/1823#issuecomment-3402118514

**Comment by istrate** [comment]
@JesperAP @pgodowski @diegovisentin I want to clarify a clear scenario here on how things are occurring. 
1. Installation is done on a new instance of SNO
2. IMO is installed on v2.21.2 but one of the `rhm-data-service-x` pods are still in `pending` state with: 
```python
0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```
3. Deleting the the CR `marketplaceconfig` will be re-recreated without the `AntiAffinity`.

- Is this a clear view of what everyone encountered? 
- Did anyone saw this during an update? If so, was the issue fixed if action from 3) was executed?

**Comment by diegovisentin** [comment]
@istrate After shutting down the operator (replicas: 0), I removed the podAntiAffinity section to deploy the three pods required by the rhm-data-service StatefulSet. This unlocks the task verification condition, allowing the pipeline to proceed to the next step. 
When I restarted the operator, the podAntiAffinity section was reestablished. For reasons that escape me, the three pods are successfully re-created anyway this time.

**Comment by istrate** [comment]
@diegovisentin the actions you did were on a new or existing deployment?

**Comment by diegovisentin** [comment]
@istrate The problem occurred during a fresh installation.
But I found the problem of the three pods that cannot start on a single server in other pre-existing SNO env. Therefore, I am concerned that the update pipeline may encounter a similar issue.

**Comment by dacleyra** [comment]
v2.21.3 is released to the certified-operators catalog.
The updated operator controller should now automatically cleanup the problematic PodAntiAffinity RequiredDuringSchedulingIgnoredDuringExecution rules that were introduced in 2.21.0.
The rules were no longer applied in v2.21.2, but lacked the logic to clean them up on an upgrade.

If you still observe a scheduling issue, please let me know.
